export default Object.freeze({
  ACCOUNT: "Account",
  AUTH: "Auth",
  ATHLETE_FEED: "AthleteFeed",
  ATHLETE_PROFILE: "AthleteProfile",
  ASK_QUESTION: "AskQuestion",
  APP: "App",
  BE_COACH: "BeCoach",
  CREATE_EVENT: "CreateEvent",
  EVENTS_FEED: "EventsFeed",
  EXPLORE: "Explore",
  EXPLORE_NEARBY: "ExploreNearbyScreen",
  EVENT_SCREEN: "EventScreen",
  FAQ: "FAQ",
  MY_PROFILE: "MyProfile",
  MY_EVENT: "MyEvents",
  MY_SETTINGS: "MySettings",
  ONBOARDING: "Onboarding",
  PRIVACY_POLICY: "PrivacyPolicy",
  REGISTER: "Register",
  REGISTER_COACH: "RegisterCoach",
  SIGN_IN: "SignIn",
  SIGN_UP: "SignUp",
  SPLASH: "Splash",
});
